# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(480, 640)
        Main.setMinimumSize(QtCore.QSize(240, 320))
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Products = QtWidgets.QWidget()
        self.Products.setObjectName("Products")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Products)
        self.verticalLayout.setObjectName("verticalLayout")
        self.productsWidget = QtWidgets.QTableWidget(self.Products)
        self.productsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.productsWidget.setColumnCount(2)
        self.productsWidget.setObjectName("productsWidget")
        self.productsWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.productsWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.productsWidget.setHorizontalHeaderItem(1, item)
        self.productsWidget.horizontalHeader().setDefaultSectionSize(49)
        self.productsWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.productsWidget)
        self.addProductButton = QtWidgets.QPushButton(self.Products)
        self.addProductButton.setObjectName("addProductButton")
        self.verticalLayout.addWidget(self.addProductButton)
        self.tabWidget.addTab(self.Products, "")
        self.Countries = QtWidgets.QWidget()
        self.Countries.setObjectName("Countries")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Countries)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.countriesWidget = QtWidgets.QTableWidget(self.Countries)
        self.countriesWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.countriesWidget.setColumnCount(2)
        self.countriesWidget.setObjectName("countriesWidget")
        self.countriesWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.countriesWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.countriesWidget.setHorizontalHeaderItem(1, item)
        self.countriesWidget.horizontalHeader().setDefaultSectionSize(49)
        self.countriesWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.countriesWidget)
        self.addCountryButton = QtWidgets.QPushButton(self.Countries)
        self.addCountryButton.setObjectName("addCountryButton")
        self.verticalLayout_3.addWidget(self.addCountryButton)
        self.tabWidget.addTab(self.Countries, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.simulateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButton.sizePolicy().hasHeightForWidth())
        self.simulateButton.setSizePolicy(sizePolicy)
        self.simulateButton.setObjectName("simulateButton")
        self.horizontalLayout.addWidget(self.simulateButton)
        self.yearsBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearsBox.sizePolicy().hasHeightForWidth())
        self.yearsBox.setSizePolicy(sizePolicy)
        self.yearsBox.setSpecialValueText("")
        self.yearsBox.setSuffix("")
        self.yearsBox.setMinimum(1)
        self.yearsBox.setMaximum(999)
        self.yearsBox.setObjectName("yearsBox")
        self.horizontalLayout.addWidget(self.yearsBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Simulation"))
        item = self.productsWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Type"))
        item = self.productsWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Name"))
        self.addProductButton.setText(_translate("Main", "Add product"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Products), _translate("Main", "Products"))
        item = self.countriesWidget.horizontalHeaderItem(0)
        item.setText(_translate("Main", "Type"))
        item = self.countriesWidget.horizontalHeaderItem(1)
        item.setText(_translate("Main", "Name"))
        self.addCountryButton.setText(_translate("Main", "Add country"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Countries), _translate("Main", "Countries"))
        self.simulateButton.setText(_translate("Main", "Simulate"))

