# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(326, 640)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.abstraction_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abstraction_label.sizePolicy().hasHeightForWidth())
        self.abstraction_label.setSizePolicy(sizePolicy)
        self.abstraction_label.setObjectName("abstraction_label")
        self.verticalLayout_3.addWidget(self.abstraction_label)
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dict_button = QtWidgets.QRadioButton(self.horizontalWidget)
        self.dict_button.setObjectName("dict_button")
        self.horizontalLayout.addWidget(self.dict_button)
        self.set_button = QtWidgets.QRadioButton(self.horizontalWidget)
        self.set_button.setObjectName("set_button")
        self.horizontalLayout.addWidget(self.set_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.horizontalWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.driver_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driver_label.sizePolicy().hasHeightForWidth())
        self.driver_label.setSizePolicy(sizePolicy)
        self.driver_label.setObjectName("driver_label")
        self.verticalLayout_3.addWidget(self.driver_label)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.custom_list_button = QtWidgets.QRadioButton(self.horizontalWidget_2)
        self.custom_list_button.setObjectName("custom_list_button")
        self.horizontalLayout_2.addWidget(self.custom_list_button)
        self.builtin_list_button = QtWidgets.QRadioButton(self.horizontalWidget_2)
        self.builtin_list_button.setObjectName("builtin_list_button")
        self.horizontalLayout_2.addWidget(self.builtin_list_button)
        self.hash_table_button = QtWidgets.QRadioButton(self.horizontalWidget_2)
        self.hash_table_button.setObjectName("hash_table_button")
        self.horizontalLayout_2.addWidget(self.hash_table_button)
        self.verticalLayout_3.addWidget(self.horizontalWidget_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.items_list = QtWidgets.QListWidget(self.centralwidget)
        self.items_list.setObjectName("items_list")
        self.verticalLayout_2.addWidget(self.items_list)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.get_by_key_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_by_key_button.setEnabled(True)
        self.get_by_key_button.setCheckable(False)
        self.get_by_key_button.setObjectName("get_by_key_button")
        self.verticalLayout_4.addWidget(self.get_by_key_button)
        self.set_by_key_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_by_key_button.setObjectName("set_by_key_button")
        self.verticalLayout_4.addWidget(self.set_by_key_button)
        self.remove_by_key_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_by_key_button.setObjectName("remove_by_key_button")
        self.verticalLayout_4.addWidget(self.remove_by_key_button)
        self.is_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.is_in_button.setEnabled(True)
        self.is_in_button.setFlat(False)
        self.is_in_button.setObjectName("is_in_button")
        self.verticalLayout_4.addWidget(self.is_in_button)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.verticalLayout_4.addWidget(self.add_button)
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setObjectName("remove_button")
        self.verticalLayout_4.addWidget(self.remove_button)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.time_status = QtWidgets.QStatusBar(MainWindow)
        self.time_status.setObjectName("time_status")
        MainWindow.setStatusBar(self.time_status)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exam"))
        self.abstraction_label.setText(_translate("MainWindow", "Abstraction:"))
        self.dict_button.setText(_translate("MainWindow", "Dictionary"))
        self.set_button.setText(_translate("MainWindow", "Set"))
        self.driver_label.setText(_translate("MainWindow", "Driver:"))
        self.custom_list_button.setText(_translate("MainWindow", "Custom List"))
        self.builtin_list_button.setText(_translate("MainWindow", "Builtin List"))
        self.hash_table_button.setText(_translate("MainWindow", "Hash Table"))
        self.get_by_key_button.setText(_translate("MainWindow", "Get by key"))
        self.set_by_key_button.setText(_translate("MainWindow", "Set by key"))
        self.remove_by_key_button.setText(_translate("MainWindow", "Remove by key"))
        self.is_in_button.setText(_translate("MainWindow", "Is in"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.remove_button.setText(_translate("MainWindow", "Remove"))

